"""이 파일은 Streamlit 세션 기본값을 담당한다."""

from __future__ import annotations

from .theme import DEFAULT_THEME_MODE

DEFAULTS = {
    "step": 1,
    "step_selector": 1,
    "product_name": "크림 베이지 65% 커스텀 키보드",
    "product_type": "커스텀 키보드",
    "price": "189,000원",
    "target_channel": "인스타그램",
    "target_customer": "깔끔한 데스크 셋업을 원하는 직장인",
    "selling_point": "조용한 타건감, 크림 톤 키캡, 작은 책상에도 잘 맞는 65% 배열",
    "layout": "65",
    "product_library": "keyboard_layout 샘플",
    "keyboard_model": "Qwertykeys Neo65",
    "drawing_upload_mode": "샘플 JSON 사용",
    "theme": "minimal",
    "case_color": "#c8c1b2",
    "keycap_color": "#f4ead7",
    "accent_keycap_color": "#6f8faf",
    "deskmat_color": "#1f2937",
    "desk_color": "#d8b892",
    "mouse_color": "#f7f7f2",
    "case_finish": "anodized",
    "plate_material": "aluminum",
    "pcb_color": "black",
    "switch_stem": "red",
    "switch_family": "mx",
    "keycap_profile": "cherry",
    "mount_type": "top_mount",
    "show_internals": False,
    "monitor_arm_style": "single",
    "desk_preset": "120 x 60 cm",
    "desk_width": 120.0,
    "desk_depth": 60.0,
    "monitor_size": "27",
    "asset_selection": ["mouse", "monitor", "monitor_arm", "desk_lamp", "plant"],
    "selected_setup_item": "keyboard",
    "camera": "perspective",
    "model_url": None,
    "model_meta": None,
    "setup_composition_b64": None,
    "setup_composition_topdown_b64": None,
    "use_setup_composition": True,
    "uploaded_model_url": None,
    "uploaded_model_meta": None,
    "library_model_path": None,
    "library_model_picker_path": None,
    "selected_history_model_path": None,
    "selected_history_model_url": None,
    "selected_history_model_meta": None,
    "selected_reference_path": None,
    "copy_result": None,
    "copy_experiment_result": None,
    "copy_selected_provider": None,
    "poster_result": None,
    "image_job_result": None,
    "image_workflow": None,
    "image_quality_report": None,
    "image_polling_enabled": False,
    "image_poll_started_at": None,
    "image_poll_timeout_seconds": 600,
    "ui_theme_mode": DEFAULT_THEME_MODE,
    "ad_tone": "감성형",
    "engine": "hyperclova",
    "engine_model_tier": "general",
    "image_ratio": "1:1",
    "extra_request": "깔끔하고 고급스러운 데스크셋업 광고 느낌",
    "poster_template": "minimal_card",
}
